// Pagefind keeps one index per language and loads the one matching `<html lang>`,
// so each edition only searches itself. The index exists only after `npm run build`.
//
// Each indexed page carries its conceptual id, kind and context line as Pagefind
// metadata (see GuidePage and HubPage). Results render from those. A result click
// reports id and position, never the URL or the query text.

import { format, type Lang } from '@/i18n';
import { track, trackAttributes, type PageKind } from '@/lib/analytics';
import { pagefindResultMatchesQuery } from '@/lib/search-relevance';

import {
  clearPendingSearch,
  flushSettledSearch,
  initialSettledSearch,
  notePendingSearch,
  type SettledSearchState,
} from './settled-search';

export interface SearchDialogConfig {
  lang: Lang;
  resultCountOne: string;
  resultCountOther: string;
  showing: string;
  loading: string;
  empty: string;
  emptyHint: string;
  unavailable: string;
}

interface ResultData {
  url: string;
  excerpt: string;
  content?: string;
  meta?: { title?: string; context?: string; id?: string; kind?: string };
}

interface Pagefind {
  init(): Promise<void>;
  search(query: string): Promise<{ results: { data(): Promise<ResultData> }[] } | null>;
  debouncedSearch(query: string): Promise<{ results: { data(): Promise<ResultData> }[] } | null>;
}

interface SearchElements {
  dialog: HTMLDialogElement;
  trigger: HTMLButtonElement;
  input: HTMLInputElement;
  clearButton: HTMLButtonElement;
  closeButton: HTMLButtonElement;
  resultsEl: HTMLElement;
  footerEl: HTMLElement;
  countEl: HTMLElement;
  fullButton: HTMLButtonElement;
  statusEl: HTMLElement;
  idleNode: HTMLElement;
}

// Built by `pagefind --site dist` (npm run build); `astro dev` has none.
const PAGEFIND_URL = '/pagefind/pagefind.js';
// A query counts as searched once the visitor stops typing for this long, or acts on it.
const SEARCH_SETTLE_MS = 1000;
// Avoid flashing the loading copy when Pagefind answers immediately.
const LOADING_INDICATOR_DELAY_MS = 150;
const PREVIEW_LIMIT = 5;
// Relevance is decided on this sample. Pagefind's own total still includes prefix fallbacks.
const MAX_CANDIDATES = 50;

export function initializeSearch(): void {
  const elements = readSearchElements();
  const config = readSearchDialogConfig(elements.dialog.dataset.config);
  const {
    dialog,
    trigger,
    input,
    clearButton,
    closeButton,
    resultsEl,
    footerEl,
    countEl,
    fullButton,
    statusEl,
    idleNode,
  } = elements;

  let pagefind: Pagefind | null = null;
  let pagefindFailed = false;
  let requestToken = 0;
  let lastQuery = '';
  let reporting: SettledSearchState = initialSettledSearch();
  let settleTimer: number | undefined;

  function noteOutcome(query: string, resultCount: number) {
    reporting = notePendingSearch(reporting, query, resultCount);
    window.clearTimeout(settleTimer);
    settleTimer = window.setTimeout(flushSearch, SEARCH_SETTLE_MS);
  }

  function flushSearch() {
    window.clearTimeout(settleTimer);
    const flushed = flushSettledSearch(reporting);
    if (flushed.report) {
      track('search', { lang: config.lang, result_count: flushed.report.resultCount });
    }
    reporting = flushed.state;
  }

  async function ensurePagefind(): Promise<Pagefind | null> {
    if (pagefind || pagefindFailed) {
      return pagefind;
    }
    try {
      const loaded: unknown = await import(/* @vite-ignore */ PAGEFIND_URL);
      if (!isPagefind(loaded)) {
        throw new Error('Pagefind did not expose the expected API.');
      }
      await loaded.init();
      pagefind = loaded;
    } catch {
      pagefindFailed = true;
      // Visitors only see the "unavailable" copy; the cause stays here for whoever runs
      // the site locally: the index is generated by the build.
      console.warn('[search] Pagefind index not found. Run `npm run build` to generate it.');
    }
    return pagefind;
  }

  function countLabel(count: number) {
    if (count === 1) {
      return config.resultCountOne;
    }
    return format(config.resultCountOther, { count });
  }

  function setFooter(text: string | null, showFullButton = false) {
    footerEl.classList.toggle('hidden', text === null);
    footerEl.classList.toggle('flex', text !== null);
    countEl.textContent = text ?? '';
    fullButton.classList.toggle('hidden', !showFullButton);
    fullButton.classList.toggle('inline-flex', showFullButton);
  }

  function showNode(node: Node) {
    resultsEl.replaceChildren(node);
  }

  function message(text: string, hint?: string) {
    const box = document.createElement('div');
    box.className =
      'flex flex-col gap-1 p-4 font-mono text-xs text-neutral-500 light:text-neutral-600';
    const first = document.createElement('p');
    first.textContent = text;
    box.append(first);
    if (hint) {
      const second = document.createElement('p');
      second.className = 'font-sans';
      second.textContent = hint;
      box.append(second);
    }
    return box;
  }

  function showIdle() {
    showNode(idleNode);
    setFooter(null);
    statusEl.textContent = '';
  }

  function renderResults(items: ResultData[], total: number, full: boolean) {
    const list = document.createElement('ul');
    list.className = 'flex flex-col gap-1';
    list.setAttribute('role', 'list');

    items.forEach((data, i) => {
      const id = data.meta?.id;
      const kind = data.meta?.kind;
      const link = document.createElement('a');
      link.href = data.url;
      link.dataset.searchResult = '';
      link.className =
        'block rounded-lg p-3 outline-offset-[-2px] transition-colors hover:bg-white/5 focus-visible:bg-white/5 light:hover:bg-black/5 light:focus-visible:bg-black/5';
      link.setAttribute('aria-labelledby', `search-result-${i}-title`);
      link.setAttribute(
        'aria-describedby',
        `search-result-${i}-context search-result-${i}-excerpt`,
      );
      if (id && isPageKind(kind)) {
        const attrs = trackAttributes('search_result_click', {
          id,
          kind,
          lang: config.lang,
          position: i + 1,
        });
        for (const [name, value] of Object.entries(attrs)) {
          link.setAttribute(name, value);
        }
      }

      const title = document.createElement('span');
      title.id = `search-result-${i}-title`;
      title.className =
        'block break-words font-display text-sm font-semibold text-neutral-100 light:text-neutral-800 sm:text-base';
      title.textContent = data.meta?.title ?? '';

      const context = document.createElement('span');
      context.id = `search-result-${i}-context`;
      context.className =
        'mt-1 block break-words font-mono text-[11px] tracking-wide text-accent-400 light:text-accent-700';
      context.textContent = data.meta?.context ?? '';

      const excerpt = document.createElement('span');
      excerpt.id = `search-result-${i}-excerpt`;
      excerpt.className =
        'mt-1.5 block break-words text-xs leading-relaxed text-neutral-400 light:text-neutral-600';
      // Pagefind escapes the page text and only adds <mark> around the matches.
      excerpt.innerHTML = data.excerpt;

      link.append(title, context, excerpt);
      const item = document.createElement('li');
      item.append(link);
      list.append(item);
    });

    showNode(list);
    if (full || items.length === total) {
      setFooter(countLabel(total));
    } else {
      setFooter(format(config.showing, { shown: items.length, total }), true);
    }
    statusEl.textContent = countLabel(total);
  }

  async function search(query: string, { full = false } = {}) {
    const token = ++requestToken;
    if (!query.trim()) {
      reporting = clearPendingSearch(reporting);
      window.clearTimeout(settleTimer);
      showIdle();
      return;
    }

    // Only shown if Pagefind is still loading or the search takes a moment.
    const loadingTimer = window.setTimeout(() => {
      if (token === requestToken) {
        showNode(message(config.loading));
      }
    }, LOADING_INDICATOR_DELAY_MS);

    try {
      const pf = await ensurePagefind();
      if (token !== requestToken) {
        return;
      }
      if (!pf) {
        showNode(message(config.unavailable));
        setFooter(null);
        statusEl.textContent = config.unavailable;
        return;
      }

      const outcome = full ? await pf.search(query) : await pf.debouncedSearch(query);
      // `null` means Pagefind superseded this debounced call with a newer one.
      if (token !== requestToken || outcome === null) {
        return;
      }

      const sample = await Promise.all(
        outcome.results.slice(0, MAX_CANDIDATES).map((result) => result.data()),
      );
      if (token !== requestToken) {
        return;
      }
      const matched = sample.filter((data) => pagefindResultMatchesQuery(query, data));

      noteOutcome(query, matched.length);
      if (matched.length === 0) {
        const text = format(config.empty, { query: query.trim() });
        showNode(message(text, config.emptyHint));
        setFooter(null);
        // The editorial "//" prefix is visual; the live region reads the sentence.
        statusEl.textContent = text.replace(/^\/\/\s*/, '');
        return;
      }
      renderResults(full ? matched : matched.slice(0, PREVIEW_LIMIT), matched.length, full);
    } finally {
      window.clearTimeout(loadingTimer);
    }
  }

  function open() {
    if (dialog.open) {
      return;
    }
    document.documentElement.style.overflow = 'hidden';
    dialog.showModal();
    input.focus();
    void ensurePagefind();
  }

  // Close button, Escape (the dialog's own `cancel`) and the backdrop all end here.
  function onClose() {
    flushSearch();
    requestToken += 1;
    lastQuery = '';
    input.value = '';
    syncClearButton();
    showIdle();
    document.documentElement.style.overflow = '';
    trigger.focus();
  }

  function resultLinks() {
    return [...resultsEl.querySelectorAll<HTMLAnchorElement>('a[data-search-result]')];
  }

  trigger.addEventListener('click', open);
  closeButton.addEventListener('click', () => dialog.close());
  dialog.addEventListener('close', onClose);
  // A click on the dialog itself (not its panel) is a click on the backdrop area.
  dialog.addEventListener('click', (event) => {
    if (event.target === dialog) {
      dialog.close();
    }
  });
  // Coming back from a result through the back/forward cache must not find it open.
  window.addEventListener('pageshow', (event) => {
    if (event.persisted && dialog.open) {
      dialog.close();
    }
  });

  function syncClearButton() {
    const hasQuery = input.value.length > 0;
    clearButton.hidden = !hasQuery;
    if (hasQuery) {
      input.setAttribute('data-query', '');
    } else {
      input.removeAttribute('data-query');
    }
  }

  function commitQuery(query: string) {
    lastQuery = query;
    syncClearButton();
    void search(query);
  }

  syncClearButton();

  input.addEventListener('input', () => {
    commitQuery(input.value);
  });

  // Keep the caret in the field when the click starts on the clear control.
  clearButton.addEventListener('mousedown', (event) => {
    event.preventDefault();
  });
  clearButton.addEventListener('click', () => {
    input.value = '';
    commitQuery('');
    input.focus();
  });

  input.addEventListener('keydown', (event) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      void search(input.value, { full: true }).then(flushSearch);
    } else if (event.key === 'ArrowDown') {
      const first = resultLinks()[0];
      if (first) {
        event.preventDefault();
        first.focus();
      }
    }
  });

  resultsEl.addEventListener('keydown', (event) => {
    if (event.key !== 'ArrowDown' && event.key !== 'ArrowUp') {
      return;
    }
    const links = resultLinks();
    const active = document.activeElement;
    const current = active instanceof HTMLAnchorElement ? links.indexOf(active) : -1;
    if (current === -1) {
      return;
    }
    event.preventDefault();
    const next = current + (event.key === 'ArrowDown' ? 1 : -1);
    if (next < 0) {
      input.focus();
    } else {
      links[Math.min(next, links.length - 1)].focus();
    }
  });

  // Bubble phase on the results list runs before BaseLayout's document click listener,
  // so `search` is flushed before `search_result_click`.
  resultsEl.addEventListener('click', (event) => {
    if (event.target instanceof Element && event.target.closest('a[data-search-result]')) {
      flushSearch();
    }
  });

  // The full list replaces the preview; move focus to its first result.
  fullButton.addEventListener('click', () => {
    void search(lastQuery, { full: true }).then(() => {
      flushSearch();
      resultLinks()[0]?.focus();
    });
  });
}

function readSearchElements(): SearchElements {
  const dialog = requireElement('search-dialog', isDialog);
  const resultsEl = requireElement('search-results', isHtmlElement);
  const idleNode = resultsEl.querySelector('[data-search-idle]');
  if (!(idleNode instanceof HTMLElement)) {
    throw new Error('Search is missing [data-search-idle].');
  }

  return {
    dialog,
    trigger: requireElement('search-trigger', isButton),
    input: requireElement('search-input', isInput),
    clearButton: requireElement('search-clear', isButton),
    closeButton: requireElement('search-close', isButton),
    resultsEl,
    footerEl: requireElement('search-footer', isHtmlElement),
    countEl: requireElement('search-count', isHtmlElement),
    fullButton: requireElement('search-full', isButton),
    statusEl: requireElement('search-status', isHtmlElement),
    idleNode,
  };
}

function requireElement<T extends Element>(
  id: string,
  accept: (element: Element) => element is T,
): T {
  const element = document.getElementById(id);
  if (!element || !accept(element)) {
    throw new Error(`Search is missing #${id}.`);
  }
  return element;
}

function isDialog(element: Element): element is HTMLDialogElement {
  return element instanceof HTMLDialogElement;
}

function isButton(element: Element): element is HTMLButtonElement {
  return element instanceof HTMLButtonElement;
}

function isInput(element: Element): element is HTMLInputElement {
  return element instanceof HTMLInputElement;
}

function isHtmlElement(element: Element): element is HTMLElement {
  return element instanceof HTMLElement;
}

function readSearchDialogConfig(raw: string | undefined): SearchDialogConfig {
  let parsed: unknown;
  try {
    parsed = JSON.parse(raw ?? '');
  } catch {
    throw new Error('Search dialog configuration is not valid JSON.');
  }
  if (!isRecord(parsed)) {
    throw new Error('Search dialog configuration is missing.');
  }

  const lang = parsed.lang;
  if (lang !== 'es' && lang !== 'en') {
    throw new Error('Search dialog configuration is missing lang.');
  }

  return {
    lang,
    resultCountOne: requireString(parsed, 'resultCountOne'),
    resultCountOther: requireString(parsed, 'resultCountOther'),
    showing: requireString(parsed, 'showing'),
    loading: requireString(parsed, 'loading'),
    empty: requireString(parsed, 'empty'),
    emptyHint: requireString(parsed, 'emptyHint'),
    unavailable: requireString(parsed, 'unavailable'),
  };
}

function requireString(record: Record<string, unknown>, key: string): string {
  const value = record[key];
  if (typeof value !== 'string') {
    throw new Error(`Search dialog configuration is missing ${key}.`);
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isPagefind(value: unknown): value is Pagefind {
  if (!isRecord(value)) {
    return false;
  }
  return (
    typeof value.init === 'function' &&
    typeof value.search === 'function' &&
    typeof value.debouncedSearch === 'function'
  );
}

function isPageKind(value: string | undefined): value is PageKind {
  return value === 'guide' || value === 'topic' || value === 'subtopic';
}
